### ISSUE TITLE
Could you publish version 1.1.0 to crates.io ?

### ISSUE THREAD

**Issue by naari3** [Ortham/svg_to_ico#29]
I want to use this library on build scripts, but current latest version on crates.io has some bugs. Thankfully its seems to was solved already on latest commit, so I using patch to use current latest version.

```toml
# on Cargo.toml
[patch.crates-io]
svg_to_ico = { git = 'https://github.com/Ortham/svg_to_ico' }
```

If you publish to crates.io, I don't need to use this patch anymore! Thank you for your consideration 🙏
